### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by zyh1122** [midasklr/yolov5ds#10]
求教在运行detectds.py文件时，出现这种错误是为什么
Traceback (most recent call last):
  File "C:/Users/zyh/Desktop/4.6/yolov5ds-main/detectds.py", line 320, in <module>
    main(opt)
  File "C:/Users/zyh/Desktop/4.6/yolov5ds-main/detectds.py", line 315, in main
    run(**vars(opt))
  File "D:\python\3.7\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:/Users/zyh/Desktop/4.6/yolov5ds-main/detectds.py", line 175, in run
    pred_color = colorEncode(mask, colorsmap).astype(np.uint8)
  File "C:/Users/zyh/Desktop/4.6/yolov5ds-main/detectds.py", line 46, in colorEncode
    np.tile(colors[label],
IndexError: index 1 is out of bounds for axis 0 with size 1

Process finished with exit code 1

**Comment by xp520** [comment]
楼上大佬解决了吗，同错
